export const types = {
    GET_REQUEST: 'GET_REQUEST',
    GET_SUCCESS: 'GET_SUCCESS',
    GET_FAILURE: 'GET_FAILURE',

    POST_SUCCESS: 'POST_SUCCESS',
    POST_REQUEST: 'POST_REQUEST',

    PUT_SUCCESS: 'PUT_SUCCESS',
    PUT_REQUEST: 'PUT_REQUEST',

    DELETE_SUCCESS: 'DELETE_SUCCESS',
    DELETE_REQUEST: 'DELETE_REQUEST',

    GET_ONE_REQUEST: 'GET_ONE_REQUEST',
    GET_ONE_SUCCESS: 'GET_ONE_SUCCESS'
};